title: 'Bug report'
labels: [bug report]
description: Create a report to help us improve


body:
  - type: markdown
    attributes:
      value: | 
          If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 'Checklist:'
      options:
        - label: "I've searched in the [docs](https://cloudforet.io/docs/) and [QnA](https://github.com/cloudforet-io/community/discussions/categories/q-a) for my answer"
          required: true
        - label: " I've included steps to reproduce the bug."
          required: true
        - label: " I've pasted the output of `microservice version`."
          required: true
          
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 'Description'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'It bugs out when ...'
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: 'To Reproduce'
      description: 'A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.'
      placeholder:
        "Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.\n
         1. Go to '...'\n
         2. Click on '....'\n
         3. Scroll down to '....'"
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'A clear and concise description of what you expected to happen.'
  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
      placeholder: 'If applicable, add screenshots to help explain your problem.'
  - type: textarea
    id: version-and-enviroment
    validations:
      required: true
    attributes:
      label: 'Version and Enviroment'
      description: 'If applicable, add screenshots to help explain your problem.'
      placeholder: "
      ```shell
      Paste the output from `microservice version` here.
      ```"
  - type: textarea
    id: log
    validations:
      required: true
    attributes:
      label: 'Logs'
      placeholder: "```
      Paste any relevant application logs here.
      ```"
