blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://cloudforet.io/docs/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/cloudforet-io/community/discussions/new
    about: Ask a question or start a discussion about Cloudforet
  - name: Chat on Discord
    url: https://github.com/cloudforet-io/community/discussions
    about: Maybe chatting with the community can help